version: '3'
services:
  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    container_name: frontend
    ports:
      - "8091:5137"

  backend:
    build: backend/.
    container_name: backend
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - BACKEND_URL=http://localhost:8090
      - FRONTEND_URL=http://localhost:5173

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres