server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: compose-postgres
    password: compose-postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

usos:
    consumer:
      key: "BvK4hkc6RfeRxnHHbmy6"
      secret: "VxhuAFJrcakrXBamjtfafaZ44k8hnw7ZtZxxtYh3"

app:
  url: ${APP_URL}